version: '3.8'
services:
  database:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
