apiVersion: apps/v1
kind: Deployment
metadata:
  name: vendure-deployment
  labels:
    app: vendure
spec:
  selector:
    matchLabels:
      app: vendure
  replicas: 1
  template:
    metadata:
      name: vendure
      labels:
        app: vendure
    spec:
      containers:
        - name: vendure
          image: registry.digitalocean.com/ecommerce-container-repo-poc/vendure:latest
          imagePullPolicy: Always
          command: ['npm', 'run', 'start:server']
          envFrom:
            - configMapRef:
                name: vendure-config
            - secretRef:
                name: vendure-secret
          ports:
            - containerPort: 3000
